#include <stdio.h>
#include <string.h>
#include "loader.h"
#include "addins.h"
#include "casiowin.h"
#include "logo.h"

static bool FindAddins_add(struct AddInList *list, u16 const *path,
                           struct CW_BFile_FileInfo *fileinfo)
{
    u16 *path_copy = PathDuplicate(path, u"\\\\fls0\\");
    if(!path_copy)
        return false;

    struct AddIn *addin = AddInList_extend(list);
    if(!addin) {
        CW_free(path_copy);
        return false;
    }

    addin->path = path_copy;
    addin->filesize = fileinfo->file_size;
    return true;
}

/* Finds all add-ins and any relevant information from the storage memory. The
   given AddInList gets all add-ins found appended to it. Returns the number of
   add-ins found on sucess, or a BFile error code if an error is encountered.
   Note that some add-ins might still have been found even if the return value
   is an error code. */
int FindAddins(struct AddInList *list)
{
    u16 found[0x10a + 1];
    u16 const *pattern = u"\\\\fls0\\*.g3a";
    struct CW_BFile_FileInfo fileinfo;
    int shandle = -1;
    int rc = CW_BFile_FindFirst(pattern, &shandle, found, &fileinfo);
    int total = 0;

    if(rc == -1 /* BFile_EntryNotFound */) {
        CW_BFile_FindClose(shandle);
        return 0;
    }

    while(rc == 0) {
        bool valid = true;

        /* We used to check for BFile_Type_Archived = 0x41 in fileinfo.type
           here. But g3a files generated by add-ins (e.g. decompressed) have
           type 0x01. So instead just exclude folders directly. */
        if(fileinfo.type == 0x00)
            valid = false;
        /* Must have a full g3a header + checksum, at least. */
        if(fileinfo.file_size < 0x7002)
            valid = false;

        // TODO: Known bug: this fails after checking Storage memory in MEMORY
        if(valid && !FindAddins_add(list, found, &fileinfo)) {
            rc = -999;
            break;
        }
        total += valid;
        rc = CW_BFile_FindNext(shandle, found, &fileinfo);
    }

    CW_BFile_FindClose(shandle);
    return rc == -16 /* BFile_EnumerateEnd */ ? total : rc;
}

//=== MMU tests ==============================================================//

void show_utlb(int row, int E)
{
    int y = 26 + 11 * row;
    if(E == -1) {
        PrintfMiniMini( 14, y, 0, "ID");
        PrintfMiniMini( 38, y, 0, "Virtual");
        PrintfMiniMini(110, y, 0, "Physical");
        PrintfMiniMini(182, y, 0, "Size");
        PrintfMiniMini(222, y, 0, "Mode");
        PrintfMiniMini(270, y, 0, "SH");
        PrintfMiniMini(294, y, 0, "WT");
        PrintfMiniMini(318, y, 0, "C");
        PrintfMiniMini(334, y, 0, "D");
        PrintfMiniMini(350, y, 0, "V");
        return;
    }

    struct MMU_UTLB_Addr addr;
    struct MMU_UTLB_Data data;
    MMU_UTLB_Get(E, &addr, &data);

    u32 src = addr.VPN << 10;
    u32 dst = data.PPN << 10;

    int valid = (addr.V != 0) && (data.V != 0);
    int size = (data.SZ1 << 1) | data.SZ0;
    char const *size_str[] = { "1k", "4k", "64k", "1M" };
    char const *access_str[] = { "K:r", "K:rw", "U:r", "U:rw" };

    u16 fg = valid ? 0 : 4;

    y += 2 * (row > 1);

    PrintfMiniMini( 14, y, fg, "%d", E);
    PrintfMiniMini( 38, y, fg, "%08X", src);
    PrintfMiniMini(110, y, fg, "%08X", dst);
    PrintfMiniMini(182, y, fg, "%s", size_str[size]);
    PrintfMiniMini(222, y, fg, "%s", access_str[data.PR]);
    PrintfMiniMini(270, y, fg, "%s", (data.SH ? "SH" : "-"));
    PrintfMiniMini(294, y, fg, "%s", (data.WT ? "WT" : "CB"));
    PrintfMiniMini(318, y, fg, "%s", (data.C ? "C" : "-"));
    PrintfMiniMini(334, y, fg, "%s", (addr.D || data.D ? "D" : "-"));
    PrintfMiniMini(350, y, fg, "%s", (addr.V && data.V ? "V" : "-"));
}

static void invalidateTLB(void)
{
    *MMUCR |= 0x00000004;
}

static void loadPages(void)
{
    // Try to load a page
    *PTEH = 0x00300000; // no ASID
    union { u32 data; struct MMU_UTLB_Data bits; } entry;
    entry.data = 0x8c700000 & 0x1fffffff;
    entry.bits.V = 1;
    entry.bits.SZ1 = 0;
    entry.bits.SZ0 = 1; // 01: 4 kB
    entry.bits.PR = 3; // U:rw
    entry.bits.C = 1;
    entry.bits.D = 0;
    entry.bits.SH = 0;
    entry.bits.WT = 0;
    *PTEL = entry.data;
    __asm__("ldtlb; nop");
}

void MMUTests(void)
{
    int scroll = 0;
    bool result = false;
    int tries = 0;

    while(true) {
        CW_Bdisp_AllClr_VRAM();
        PrintfMini(5, 25, "MMUCR=%08x (result=%s/%d)",
            *MMUCR, result ? "true" : "false", tries);

        show_utlb(2, -1);
        for(int i = 0; i < 12; i++) {
            int E = scroll + i;
            if(E >= 64)
                break;
            show_utlb(3+i, E);
        }

        int key;
        CW_GetKey(&key);

        if(key == KEY_CTRL_DOWN && scroll < 64 - 12)
            scroll++;
        if(key == KEY_CTRL_UP && scroll > 0)
            scroll--;
        if(key == KEY_CTRL_EXIT)
            break;
        if(key == KEY_CTRL_PGUP) {
            invalidateTLB();
            MMU_SetEnabled(true);
            loadPages();
        }
        if(key == KEY_CTRL_PGDOWN)
            MMU_SetEnabled(false);
        if(key == KEY_CTRL_SETUP && MMU_IsEnabled()) {
            result = true;
            u32 const *p1 = (void *)0x00300000;
            u32 const *p2 = (void *)0x8c700000;
            for(int i = 0; i < 4096 / 4; i++) {
                if(p1[i] != p2[i]) {
                    result = false;
                    break;
                }
            }
            tries++;
        }
    }
}

static int load_addin(struct AddIn *addin, u32 *loadAddress)
{
    if(addin->filesize > (3 << 20))
        return -1001;

    void *romAddress = (void *)0x8c400000;
    void *ramAddress = (void *)0x8c780000;

    int fd = CW_BFile_Open(addin->path, CW_BFile_ReadOnly);
    if(fd < 0)
        return fd;

    /* Skip the header, load only the code */
    int read_size = addin->filesize - 0x7000;
    if(loadAddress)
        *loadAddress = (u32)romAddress;
    int rc = CW_BFile_Read(fd, romAddress, read_size, 0x7000);
    CW_BFile_Close(fd);
    if(rc < 0 || rc != read_size)
        return rc;

    /* Map the entire range (why the heck not?!) */
    for(int i = 0; i < 48; i++) {
        MMU_Map((void *)0x00300000 + (i << 16), romAddress + (i << 16),
                0x10000, i);
    }
    /* Map user RAM */
    for(int i = 0; i < 8; i++) {
        MMU_Map((void *)0x08100000 + (i << 16), ramAddress + (i << 16),
                0x10000, 55 + i);
    }
    /* Map NULL to ROM for read-only access */
    MMU_Map((void *)0x00000000, (void *)0xa0000000, 0x1000, 63);

    /* Reset URC to 0 to avoid erasing the protected region */
    *MMUCR &= 0xffff03ff;
    __asm__("icbi @%0":: "r"(0xa0000000));

    /* Replace add-in entry with "rts; nop" */
    // *(u32 *)romAddress = 0x000b0009;

    /* Invalidate caches; this also writes back reads to ROM load area */
    u32 volatile *CCR = (void *)0xff00001c;
    *CCR |= (1 << 11) // Instruction Cache Invalidate
          + (1 << 3); // Operand Cache Invalidate
    __asm__("icbi @%0":: "r"(0xa0000000));

    return rc;
}

#define MPM_VERSION_MAJOR 1
#define MPM_VERSION_MINOR 0

static void show_addin_details(struct AddIn *addin)
{
    if(!addin)
        return;

    CW_Bdisp_AllClr_VRAM();
    char str[64];
    int y = 30;

    PathToStr(str, sizeof str, addin->path);
    PrintfMini(8, y, "%s (%d kB)", str, (addin->filesize + 512) >> 10);

    if(addin->metadata_error)
        PrintfMiniMini(8, y+18, 4, "Metadata: error %d", addin->metadata_error);
    else if(addin->metadata_loaded) {
         PrintfMiniMini(8, y+18, 0, "'%.16s' '%.11s' '%.10s' '%.14s'",
             addin->name, addin->internal, addin->version, addin->date);

        AddIn_render_icon(addin, 8, y+60, false);
        AddIn_render_icon(addin, 108, y+60, true);
    }

    int key;
    CW_GetKey(&key);
}

static bool show_mapping(int rc)
{
    int offset = 0;
    int key;

    while(true) {
        CW_Bdisp_AllClr_VRAM();
        u32 *ptr1 = (void *)0x8c400000;
        u32 *ptr2 = (void *)0xac400000;
        u32 *ptr3 = (void *)0x00300000;
        for(int i = 0; i < 10; i++) {
            PrintfMiniMini(  8, 24+14*i, 0, "%06x:", (i+offset)*4);
            PrintfMiniMini( 98, 24+14*i, 0, "%08x", ptr1[i+offset]);
            PrintfMiniMini(198, 24+14*i, 0, "%08x", ptr2[i+offset]);
            PrintfMiniMini(298, 24+14*i, 0, "%08x", ptr3[i+offset]);
        }
        PrintfMini(8, 176, "rc=%d", rc);
        PrintfMini(8, 196, "EXE to load, BACK to abort");
        CW_GetKey(&key);

        if(key == KEY_CTRL_EXE)
            return true;
        if(key == KEY_CTRL_EXIT)
            return false;
        if(key == KEY_CTRL_UP && offset > 0)
            offset -= 10;
        if(key == KEY_CTRL_DOWN)
            offset += 10;
    }
}

static void run_addin(u32 loadAddress)
{
    u32 loadinfo[] = {
        0x00000001, 0x00000001,  // Info format version
        0x00000010, 0x8c200000,  // Start of an available RAM area
        0x00000011, loadAddress, // End of an available RAM area
        0x00000000,
    };

    // TODO: Move the stack pointer!!
    int (*code)(int sig, u32 *loadinfo) = (void *)0x00300000;
    int rc = code(0x4d504d30 /* 'MPM0' */, loadinfo);

    /* Ignore return code for now. */
    (void)rc;
}

int main(void)
{
    u16 *VRAM = CW_GetVRAMAddress();
    char str[64];

    int return_action = RETURN_MAIN_MENU;

    struct AddInList addins;
    addins.capacity = 0;
    addins.size = 0;

    int rc = 0;
    bool update = true;
    int cursor = 0;

    while(1) {
        CW_Bdisp_AllClr_VRAM();
        
        if (update)
        {
            AddInList_clear(&addins);
            AddInList_init(&addins, 256);
            rc = FindAddins(&addins);
            for(int i = 0; i < AddInList_size(&addins); i++)
                AddIn_load_metadata(AddInList_get(&addins, i));
            update = false;
        }

        for(int i = 0; i < 384 * 23; i++)
            VRAM[i] = 0x0000;

        PrintMini(159, 5, "ADD-INS", 0xffff);
        Logo_Render(CW_GetVRAMAddress(), 328, 6, 384);

        sprintf(str, "%d.%d", MPM_VERSION_MAJOR, MPM_VERSION_MINOR);
        {int x = 362, y = 10;
         CW_PrintMiniMini(&x, &y, str, 0x44, 0, 0);}

        if(rc < 0) {
            PrintfMini(8, 30, "Error enumerating add-ins: %d", rc);
        }
        else if(AddInList_size(&addins) == 0) {
            PrintMini(8, 30, "No add-ins!", 0x0000);
        }
        else for(int i = 0; i < AddInList_size(&addins); i++) {
            struct AddIn const *addin = AddInList_get(&addins, i);
            int icon_y = 24 + 64 * (i / 4);
            int icon_x = 92 * (i % 4);
            bool selected = (cursor == i);

            if(addin->metadata_error) {
                PrintfMiniMini(icon_x, icon_y, 4, "Err %d",
                    addin->metadata_error);
            }
            else if(!addin->metadata_loaded) {
                PathToStr(str, sizeof str, addin->path);
                PrintfMiniMini(icon_x, icon_y, 0, str);
            }
            else {
                AddIn_render_icon(addin, icon_x, icon_y, selected);
            }
        }

        // TODO: SETTINGS menu
        // PrintMini(8, 194, "[+]: MMU info", 0x0000);

        extern void CW_BatteryIcon(int);
        extern int CW_UpdateBatteryState(void);
        CW_BatteryIcon(CW_UpdateBatteryState());

        int key;
        CW_GetKey(&key);

        if(key == KEY_CTRL_EXIT || key == KEY_CTRL_MENU || key == KEY_CTRL_TOOLS)
            break;
        if(key == KEY_CTRL_CATALOG)
        {
            CW_INTERNAL_USBPopup();
            update = true;
        }
        if(key == KEY_CHAR_PLUS)
            MMUTests();

        int next_cursor = cursor;
        if(key == KEY_CTRL_UP)
            next_cursor -= 4;
        if(key == KEY_CTRL_DOWN)
            next_cursor += 4;
        if(key == KEY_CTRL_LEFT)
            next_cursor--;
        if(key == KEY_CTRL_RIGHT)
            next_cursor++;
        if(next_cursor >= 0 && next_cursor < AddInList_size(&addins))
            cursor = next_cursor;
        else if (next_cursor<0)
            cursor = AddInList_size(&addins)-1;
        else cursor = 0;

        
        if(key == KEY_CTRL_VARS)
            show_addin_details(AddInList_get(&addins, cursor));
        if(key == KEY_CTRL_EXE || key == KEY_CTRL_FORMAT) {
            struct AddIn *addin = AddInList_get(&addins, cursor);
            if(addin) {
                u32 loadAddress;
                MMU_SetEnabled(true);
                int rc = load_addin(addin, &loadAddress);
                int run = true;

                if(key == KEY_CTRL_FORMAT)
                    run = show_mapping(rc);
                if(run)
                    run_addin(loadAddress);

                MMU_SetEnabled(false);
                CW_DrawFrame(0x0000);
            }
            update = true;
        }
    }

    AddInList_clear(&addins);

    for(int i = 5; i < 10; i++)
        CW_Timer_Deinstall(i);

    return return_action;
}
